name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libsqlite3-dev
          bundle install
      - name: Rspec
        run: bundle exec rspec
